In [28]:
#Gerekli kütüphaneler
import pandas as pd
import numpy as np
import random

In [29]:
#RNA-Seq veriseti dosyası okunup sütun adı değiştirildi
gedf = pd.read_csv("../data/GSE54456_RPKM_samples.txt", sep="\t")
gedf.rename(columns={"Unnamed: 0" : "gene"}, inplace=True)
gedf

,gene,M3059,M3171,M3418,M3978,M4208,M4257,M4271,M4277,M4284,...,M8883,M8900,M8979,M9000,M9003,M9004,M9027,M9049,M9081,M9132
0,AAAS,13.712,9.345,17.459,19.250,15.470,9.397,13.3425,14.3215,15.195,...,16.674,12.272,14.057,13.072,11.375,14.525,14.820,14.033,14.205,11.844
1,AAA1,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.0000,0.022,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,AACS,20.291,25.723,19.216,13.986,20.635,9.865,17.5790,46.1495,25.680,...,53.276,57.345,67.625,49.758,42.008,34.581,44.628,20.623,17.300,16.317
3,AACSL,0.187,0.114,0.382,0.153,0.515,0.273,0.4175,0.1805,0.683,...,0.207,0.180,0.089,0.070,0.000,0.180,0.034,0.054,0.139,0.269
4,AADAC,1.453,0.257,2.620,3.590,0.348,0.763,5.8995,2.8880,1.593,...,8.099,1.575,1.616,4.213,2.279,5.694,9.987,0.329,2.198,0.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21505,ZYX,59.727,83.595,76.981,56.323,58.261,39.521,29.9760,47.4165,47.308,...,86.110,47.357,47.381,72.105,71.588,48.301,71.440,58.756,65.476,49.404
21506,ZZEF1,5.862,5.842,10.164,7.718,6.968,7.259,6.8000,8.8775,6.411,...,7.022,7.360,9.173,8.619,7.015,7.776,6.070,6.753,7.516,7.106
21507,ZZZ3,3.147,0.916,6.713,6.018,4.140,9.666,8.1790,8.7420,5.052,...,5.236,6.433,5.972,6.169,4.845,9.621,4.612,5.567,4.637,7.001
21508,psiTPTE22,0.995,1.616,1.721,0.465,2.817,0.414,1.2645,2.8155,3.490,...,3.051,3.541,3.634,3.407,4.084,1.276,3.787,1.192,0.444,1.967
21509,tAKR,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.0000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.057

In [30]:
#TF-Target veriseti okunup birleştirme için ortak sütun belirlendi.
ttdf = pd.read_csv("../data/tf-target.txt")
ttdf.rename(columns={"tf":"gene"}, inplace=True)
ttdf

       gene  target mode_of_regulation    references_PMID
0      AATF     BAX         Repression           22909821
1      AATF  CDKN1A            Unknown           17157788
2      AATF    KLK3            Unknown           23146908
3      AATF     MYC         Activation           20549547
4      AATF    TP53            Unknown           17157788
...     ...     ...                ...                ...
9391  ZNF76  CDKN1A         Repression           15280358
9392  ZNF76  PCYT1A         Activation           14702349
9393  ZNF76  TALDO1            Unknown           14702349
9394  ZNRD1   ABCB1         Activation           16373708
9395  ZNRD1    BCL2         Activation  16373708;16609701

[9396 rows x 4 columns]

In [31]:
#TF-Target çiftleri için RNA-seq değeri eşleştirildi
mdf = ttdf.merge(gedf)
#Gerekli olmayan sütunlar düşürüldü
genel_df2 = mdf.drop(["references_PMID","mode_of_regulation"], axis=1)
#Bu çiftler için yeni bir class oluşturuldu "pair" sütunu eğitimde bizim etiketimiz olacak
genel_df2["pair"] = 1
genel_df2

,gene,target,M3059,M3171,M3418,M3978,M4208,M4257,M4271,M4277,...,M8900,M8979,M9000,M9003,M9004,M9027,M9049,M9081,M9132,pair
0,AATF,BAX,21.679,12.681,24.530,25.282,18.916,20.570,30.5765,26.733,...,24.155,19.358,21.683,19.651,26.551,23.127,16.885,25.671,19.741,1
1,AATF,CDKN1A,21.679,12.681,24.530,25.282,18.916,20.570,30.5765,26.733,...,24.155,19.358,21.683,19.651,26.551,23.127,16.885,25.671,19.741,1
2,AATF,KLK3,21.679,12.681,24.530,25.282,18.916,20.570,30.5765,26.733,...,24.155,19.358,21.683,19.651,26.551,23.127,16.885,25.671,19.741,1
3,AATF,MYC,21.679,12.681,24.530,25.282,18.916,20.570,30.5765,26.733,...,24.155,19.358,21.683,19.651,26.551,23.127,16.885,25.671,19.741,1
4,AATF,TP53,21.679,12.681,24.530,25.282,18.916,20.570,30.5765,26.733,...,24.155,19.358,21.683,19.651,26.551,23.127,16.885,25.671,19.741,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9373,ZNF76,CDKN1A,7.576,12.561,9.372,5.579,9.484,3.570,5.1230,5.985,...,6.620,9.392,9.548,7.031,7.376,7.245,5.647,6.758,5.228,1
9374,ZNF76,PCYT1A,7.576,12.561,9.372,5.579,9.484,3.570,5.1230,5.985,...,6.620,9.392,9.548,7.031,7.376,7.245,5.647,6.758,5.228,1
9375,ZNF76,TALDO1,7.576,12.561,9.372,5.579,9.484,3.570,5.1230,5.985,...,6.620,9.392,9.548,7.031,7.376,7.245,5.647,6.758,5.228,1
9376,ZNRD1,ABCB1,13.823,20.818,16.820,13.047,18.234,8.655,13.7315,9.942,...,10.921,15.225,11.776,13.944,13.725,10.553,9.504,12.461,11.247,1
9377,ZNRD1,BCL2,13.823,20.818,16.820,13.047,18.234,8.655,13.7315,9.942,...,10.921,15.225,11.776,13.944,13.725,10.553,9.504,12.461,11.247,1

In [32]:
#Rastgele tf-target çiftleri oluşturuldu.
lst = gedf["gene"]
lst = list(lst)
def pop_random(lst):
    idx = random.randrange(0, len(lst))
    return lst.pop(idx)
pairs = []
while lst:
    rand1 = pop_random(lst)
    rand2 = pop_random(lst)
    pair = rand1, rand2
    pairs.append(pair)

In [33]:
generated_df = pd.DataFrame(pairs)
generated_df.rename(columns={0:"gene",1:"target"}, inplace=True)
#Bilinen TF-Target çiftleri ile eşit sayıda olması için oluşan dataframe sınırlandırıldı.
short_gdf = generated_df.iloc[:9378,:]
#Rastgele oluşturulan TF-Target çiftleri için RNA-seq değerleri eşleştirildi
false_shortdf = short_gdf.merge(gedf)
#Bu çiftler için class'ımız olan "pair" sütunu 0 olarak atandı.
false_shortdf["pair"] = 0
false_shortdf

,gene,target,M3059,M3171,M3418,M3978,M4208,M4257,M4271,M4277,...,M8900,M8979,M9000,M9003,M9004,M9027,M9049,M9081,M9132,pair
0,OR9A4,GPX1,0.000,0.000,0.000,0.000,0.000,0.000,0.0205,0.0230,...,0.000,0.041,0.040,0.000,0.000,0.000,0.000,0.000,0.000,0
1,SMC2,SPON1,2.332,0.547,3.724,3.828,3.138,7.269,9.0660,5.2775,...,3.051,2.085,1.918,1.685,3.986,2.480,3.234,3.602,5.626,0
2,HBG2,HIST1H3J,0.000,0.000,0.633,0.311,1.151,0.000,0.0000,0.0750,...,0.000,0.266,1.370,0.000,0.279,0.064,0.202,0.104,0.318,0
3,KCP,EID2B,0.229,0.215,0.160,0.126,0.292,0.294,0.0785,0.1345,...,0.115,0.128,0.225,0.279,0.085,0.149,0.112,0.052,0.124,0
4,SORD,SNRNP27,18.052,21.625,16.444,19.022,21.701,23.613,21.2995,48.8900,...,46.444,28.577,17.880,18.060,43.381,21.434,17.033,17.286,20.659,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9373,MELK,BACH1,3.081,0.744,4.273,5.749,3.532,5.273,8.0415,1.3935,...,1.310,0.827,0.702,0.986,0.948,1.378,3.470,4.420,4.308,0
9374,RNF214,DPP10,2.155,1.872,5.906,4.489,4.052,4.891,5.7515,5.5320,...,4.543,3.887,4.190,3.833,5.387,4.263,3.549,3.469,3.582,0
9375,BCAM,ZNF28,26.187,30.989,23.612,21.689,23.015,13.008,10.4820,32.3825,...,30.123,31.067,44.330,51.909,32.511,49.121,21.368,22.926,19.720,0
9376,RCBTB1,TRIM7,1.485,1.677,3.132,3.116,2.634,4.393,3.3935,5.6430,...,3.787,3.853,3.282,2.681,4.392,3.572,2.499,2.148,3.235,0
9377,MMP15,GFPT1,3.250,4.203,2.536,3.882,3.757,1.649,1.6160,3.3020,...,3.654,5.584,4.631,4.619,2.364,3.897,3.517,2.668,2.846,0

In [34]:
clean_df

,target,target,M3059,M3171,M3418,M3978,M4208,M4257,M4271,M4277,...,M8900,M8979,M9000,M9003,M9004,M9027,M9049,M9081,M9132,pair
0,SASS6,MITD1,0.573,0.148,0.994,0.830,0.459,4.364,2.0640,1.0495,...,0.572,0.438,0.439,0.206,0.895,0.335,0.641,0.682,1.083,0
1,UBE2F,PDE4B,31.299,28.128,25.048,22.039,37.469,44.328,38.3070,16.7850,...,15.062,17.131,13.931,11.180,14.370,14.946,31.735,34.984,35.563,0
2,WDR33,GRPEL1,3.884,2.127,5.366,5.009,3.959,6.297,6.1080,6.2030,...,5.199,3.756,3.891,4.650,5.272,3.590,4.179,5.146,5.008,0
3,ADH4,TMEM62,0.000,0.000,0.000,0.076,0.057,0.107,0.0200,0.1265,...,0.091,0.000,0.000,0.260,0.132,0.057,0.030,0.031,0.040,0
4,AMAC1L2,AMIGO1,0.000,0.069,0.051,0.025,0.093,0.035,0.0000,0.1250,...,0.025,0.032,0.063,0.000,0.081,0.186,0.049,0.050,0.044,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18751,ZNF76,CDKN1A,7.576,12.561,9.372,5.579,9.484,3.570,5.1230,5.9850,...,6.620,9.392,9.548,7.031,7.376,7.245,5.647,6.758,5.228,1
18752,ZNF76,PCYT1A,7.576,12.561,9.372,5.579,9.484,3.570,5.1230,5.9850,...,6.620,9.392,9.548,7.031,7.376,7.245,5.647,6.758,5.228,1
18753,ZNF76,TALDO1,7.576,12.561,9.372,5.579,9.484,3.570,5.1230,5.9850,...,6.620,9.392,9.548,7.031,7.376,7.245,5.647,6.758,5.228,1
18754,ZNRD1,ABCB1,13.823,20.818,16.820,13.047,18.234,8.655,13.7315,9.9420,...,10.921,15.225,11.776,13.944,13.725,10.553,9.504,12.461,11.247,1
18755,ZNRD1,BCL2,13.823,20.818,16.820,13.047,18.234,8.655,13.7315,9.9420,...,10.921,15.225,11.776,13.944,13.725,10.553,9.504,12.461,11.247,1

In [42]:
#Hem doğru hem de uydurulmuş tf-target dataframeler birleştirildi
clean_df = pd.concat([false_shortdf, genel_df2])
#indeks resetlendi
clean_df.reset_index(drop=True, inplace=True)
#sadece tf için değil aynı zamanda hedef gen için de rna-seq değerleri birleştirildi
#böylelikle sütun sayısı 2 katına çıkmış oldu.
#satır sayısı da sahte çiftler ile birlikte 2 katına çıkmış oldu.
gedf.rename(columns={"gene":"target"}, inplace=True)
merge_df = clean_df.merge(gedf, on="target")
merge_df.to_csv("double_expression_dataframe.txt", index=False, encoding="utf-8-sig")
merge_df

,gene,target,M3059_x,M3171_x,M3418_x,M3978_x,M4208_x,M4257_x,M4271_x,M4277_x,...,M8883_y,M8900_y,M8979_y,M9000_y,M9003_y,M9004_y,M9027_y,M9049_y,M9081_y,M9132_y
0,OR9A4,GPX1,0.000,0.000,0.000,0.000,0.000,0.000,0.0205,0.0230,...,85.088,60.594,76.966,78.551,101.715,64.654,91.188,98.838,73.991,73.995
1,TFAP2C,GPX1,24.395,17.257,31.088,31.042,31.755,47.942,41.4945,32.5865,...,85.088,60.594,76.966,78.551,101.715,64.654,91.188,98.838,73.991,73.995
2,SMC2,SPON1,2.332,0.547,3.724,3.828,3.138,7.269,9.0660,5.2775,...,12.700,11.642,8.322,10.390,12.925,11.349,6.647,9.938,5.235,11.138
3,HBG2,HIST1H3J,0.000,0.000,0.633,0.311,1.151,0.000,0.0000,0.0750,...,0.134,0.063,0.162,0.159,0.000,0.273,0.078,0.370,0.063,0.167
4,KCP,EID2B,0.229,0.215,0.160,0.126,0.292,0.294,0.0785,0.1345,...,0.894,0.759,0.478,0.612,0.890,0.681,0.580,0.299,0.275,0.355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18587,ZNF143,BUB1B,3.687,3.360,4.622,4.307,4.213,4.679,5.4080,5.6650,...,1.097,0.894,0.746,0.864,0.612,1.349,1.068,2.679,2.268,2.936
18588,ZNF143,ESCO2,3.687,3.360,4.622,4.307,4.213,4.679,5.4080,5.6650,...,0.363,0.386,0.300,0.125,0.136,0.340,0.456,0.823,0.612,1.138
18589,ZNF143,PCYT1A,3.687,3.360,4.622,4.307,4.213,4.679,5.4080,5.6650,...,27.140,24.645,23.232,26.585,21.719,24.617,21.950,27.758,31.849,26.772
18590,ZNF76,PCYT1A,7.576,12.561,9.372,5.579,9.484,3.570,5.1230,5.9850,...,27.140,24.645,23.232,26.585,21.719,24.617,21.950,27.758,31.849,26.772
18591,ZNF350,TRIM28,1.953,0.705,3.219,1.976,2.534,3.146,3.5185,5.9485,...,84.653,80.424,113.953,107.585,113.079,81.035,106.133,84.043,104.937,70.175